import { DEFAULT_PIVOT_YEAR, Event } from "./types";

// pivotYear = 0 means year 0 on the cosmic scale (used for cosmological events).
// Events with pivotYear = DEFAULT_PIVOT_YEAR (current year) behave like the old
// "year from now" system where positive = future, negative = past.
export const EVENTS: Event[] = [
  {
    id: "big-bang",
    title: "Big Bang",
    description: "The beginning of the universe.",
    absoluteYear: -13800000000,
    pivotYear: 0, // Cosmic scale: year 0 is the pivot
    emoji: "💥",
    groups: ["Cosmic History"],
    priority: 100,
  },
  {
    id: "earth-formed",
    title: "Earth Formed",
    description: "Formation of the Earth.",
    absoluteYear: -4500000000,
    pivotYear: 0,
    emoji: "🌍",
    groups: ["Cosmic History", "Earth History"],
    priority: 90,
  },
  {
    id: "life-begins",
    title: "Life Begins",
    description: "First signs of life on Earth.",
    absoluteYear: -3800000000,
    pivotYear: 0,
    emoji: "🦠",
    groups: ["Earth History", "Biology"],
    priority: 85,
  },
  {
    id: "dinosaurs-extinct",
    title: "Dinosaurs Extinct",
    description: "Asteroid impact.",
    absoluteYear: -66000000,
    pivotYear: 0,
    emoji: "🦖",
    groups: ["Earth History", "Biology"],
    priority: 80,
  },
  {
    id: "human-civilization",
    title: "Human Civilization",
    description: "Rise of early civilizations.",
    absoluteYear: -8000,
    pivotYear: 0,
    emoji: "🏛️",
    groups: ["Human History"],
    priority: 70,
  },
  {
    id: "pyramids",
    title: "Great Pyramid of Giza",
    description: "Construction of the Great Pyramid.",
    absoluteYear: -2500,
    pivotYear: 0,
    emoji: "🔺",
    groups: ["Human History", "Monuments"],
    priority: 60,
  },
  {
    id: "rome-falls",
    title: "Fall of Rome",
    description: "The fall of the Western Roman Empire.",
    absoluteYear: 476,
    pivotYear: DEFAULT_PIVOT_YEAR,
    emoji: "🏛️",
    groups: ["Human History", "Empires"],
    priority: 55,
  },
  {
    id: "industrial-revolution",
    title: "Industrial Revolution",
    description: "Transition to new manufacturing processes.",
    absoluteYear: 1760,
    pivotYear: DEFAULT_PIVOT_YEAR,
    emoji: "🏭",
    groups: ["Human History", "Technology"],
    priority: 65,
  },
  {
    id: "moon-landing",
    title: "Moon Landing",
    description: "Apollo 11 lands on the moon.",
    absoluteYear: 1969,
    pivotYear: DEFAULT_PIVOT_YEAR,
    emoji: "🌕",
    groups: ["Human History", "Technology", "Space"],
    priority: 75,
  },
  {
    id: "internet",
    title: "Internet Invented",
    description: "ARPANET adopts TCP/IP.",
    absoluteYear: 1983,
    pivotYear: DEFAULT_PIVOT_YEAR,
    emoji: "🌐",
    groups: ["Human History", "Technology"],
    priority: 70,
  },
  {
    id: "smartphone",
    title: "First Smartphone",
    description: "iPhone released.",
    absoluteYear: 2007,
    pivotYear: DEFAULT_PIVOT_YEAR,
    emoji: "📱",
    groups: ["Human History", "Technology"],
    priority: 60,
  },
  {
    id: "covid",
    title: "COVID-19 Pandemic",
    description: "Global pandemic begins.",
    absoluteYear: 2020,
    pivotYear: DEFAULT_PIVOT_YEAR,
    emoji: "😷",
    groups: ["Human History", "Recent"],
    priority: 65,
  },
  // {
  //   id: "one-day-ago",
  //   title: "Yesterday",
  //   description: "Just 24 hours ago.",
  //   absoluteYear: ...,  // compute from pivotYear
  //   pivotYear: DEFAULT_PIVOT_YEAR,
  //   emoji: "🌅",
  //   groups: ["Recent"],
  //   priority: 10,
  // },
  // {
  //   id: "one-hour-ago",
  //   title: "An Hour Ago",
  //   description: "60 minutes ago.",
  //   absoluteYear: ...,  // compute from pivotYear
  //   pivotYear: DEFAULT_PIVOT_YEAR,
  //   emoji: "⏳",
  //   groups: ["Recent"],
  //   priority: 5,
  // },
  // {
  //   id: "today",
  //   title: "Present Moment",
  //   description: "Right now.",
  //   absoluteYear: DEFAULT_PIVOT_YEAR,
  //   pivotYear: DEFAULT_PIVOT_YEAR,
  //   emoji: "📍",
  //   groups: ["Recent"],
  //   priority: 100,
  // },
];
