import { Event } from "./types";

export const BIG_BANG_YEAR = -13.8e9;

export const EVENTS: Event[] = [
  {
    id: "big-bang",
    title: "Big Bang",
    description: "The beginning of the universe.",
    time: [BIG_BANG_YEAR, null, null, null, null, null],
    emoji: "💥",
    groups: ["Cosmic History"],
    priority: 100,
  },
  {
    id: "earth-formed",
    title: "Earth Formed",
    description: "Formation of the Earth.",
    time: [-4500000000, null, null, null, null, null],
    emoji: "🌍",
    groups: ["Cosmic History", "Earth History"],
    priority: 90,
  },
  {
    id: "life-begins",
    title: "Life Begins",
    description: "First signs of life on Earth.",
    time: [-3800000000, null, null, null, null, null],
    emoji: "🦠",
    groups: ["Earth History", "Biology"],
    priority: 85,
  },
  {
    id: "dinosaurs-extinct",
    title: "Dinosaurs Extinct",
    description: "Asteroid impact.",
    time: [-66000000, null, null, null, null, null],
    emoji: "🦖",
    groups: ["Earth History", "Biology"],
    priority: 80,
  },
  {
    id: "human-civilization",
    title: "Human Civilization",
    description: "Rise of early civilizations.",
    time: [-8000, null, null, null, null, null],
    emoji: "🏛️",
    groups: ["Human History"],
    priority: 70,
  },
  {
    id: "pyramids",
    title: "Great Pyramid of Giza",
    description: "Construction of the Great Pyramid.",
    time: [-2500, null, null, null, null, null],
    emoji: "🔺",
    groups: ["Human History", "Monuments"],
    priority: 60,
  },
  {
    id: "rome-falls",
    title: "Fall of Rome",
    description: "The fall of the Western Roman Empire.",
    time: [476, null, null, null, null, null],
    emoji: "🏛️",
    groups: ["Human History", "Empires"],
    priority: 55,
  },
  {
    id: "industrial-revolution",
    title: "Industrial Revolution",
    description: "Transition to new manufacturing processes.",
    time: [1760, null, null, null, null, null],
    emoji: "🏭",
    groups: ["Human History", "Technology"],
    priority: 65,
  },
  {
    id: "moon-landing",
    title: "Moon Landing",
    description: "Apollo 11 lands on the moon.",
    time: [1969, null, null, null, null, null],
    duration: 1,
    emoji: "🌕",
    groups: ["Human History", "Technology", "Space"],
    priority: 75,
  },
  {
    id: "internet",
    title: "Internet Invented",
    description: "ARPANET adopts TCP/IP.",
    time: [1983, null, null, null, null, null],
    emoji: "🌐",
    groups: ["Human History", "Technology"],
    priority: 70,
  },
  {
    id: "smartphone",
    title: "First Smartphone",
    description: "iPhone released.",
    time: [2007, null, null, null, null, null],
    emoji: "📱",
    groups: ["Human History", "Technology"],
    priority: 60,
  },
  {
    id: "covid",
    title: "COVID-19 Pandemic",
    description: "Global pandemic begins.",
    time: [2020, null, null, null, null, null],
    emoji: "😷",
    groups: ["Human History", "Recent"],
    priority: 65,
  },
];
