import { Event } from "./types";

export const BIG_BANG_YEAR = -13.8e9;

export const EVENTS: Event[] = [
  {
    id: "big-bang",
    title: "Big Bang",
    description: "The beginning of the universe.",
    time: [BIG_BANG_YEAR, null, null, null, null, null],
    emoji: "💥",
    groups: ["Cosmic History"],
    priority: 100,
  },
  {
    id: "earth-formed",
    title: "Earth Formed",
    description: "Formation of the Earth.",
    time: [-4500000000, null, null, null, null, null],
    emoji: "🌍",
    groups: ["Cosmic History", "Earth History"],
    priority: 90,
  },
  {
    id: "life-begins",
    title: "Life Begins",
    description: "First signs of life on Earth.",
    time: [-3800000000, null, null, null, null, null],
    emoji: "🦠",
    groups: ["Earth History", "Biology"],
    priority: 85,
  },
  {
    id: "dinosaurs-extinct",
    title: "Dinosaurs Extinct",
    description: "Asteroid impact.",
    time: [-66000000, null, null, null, null, null],
    emoji: "🦖",
    groups: ["Earth History", "Biology"],
    priority: 80,
  },
  {
    id: "human-civilization",
    title: "Human Civilization",
    description: "Rise of early civilizations.",
    time: [-8000, null, null, null, null, null],
    emoji: "🏛️",
    groups: ["Human History"],
    priority: 70,
  },
  {
    id: "pyramids",
    title: "Great Pyramid of Giza",
    description: "Construction of the Great Pyramid.",
    time: [-2500, null, null, null, null, null],
    emoji: "🔺",
    groups: ["Human History", "Monuments"],
    priority: 60,
  },
  {
    id: "rome-falls",
    title: "Fall of Rome",
    description: "The fall of the Western Roman Empire.",
    time: [476, null, null, null, null, null],
    emoji: "🏛️",
    groups: ["Human History", "Empires"],
    priority: 55,
  },
  {
    id: "industrial-revolution",
    title: "Industrial Revolution",
    description: "Transition to new manufacturing processes.",
    time: [1760, null, null, null, null, null],
    emoji: "🏭",
    groups: ["Human History", "Technology"],
    priority: 65,
  },
  {
    id: "moon-landing",
    title: "Moon Landing",
    description: "Apollo 11 lands on the moon.",
    time: [1969, null, null, null, null, null],
    duration: 1,
    emoji: "🌕",
    groups: ["Human History", "Technology", "Space"],
    priority: 75,
  },
  {
    id: "internet",
    title: "Internet Invented",
    description: "ARPANET adopts TCP/IP.",
    time: [1983, null, null, null, null, null],
    emoji: "🌐",
    groups: ["Human History", "Technology"],
    priority: 70,
  },
  {
    id: "smartphone",
    title: "First Smartphone",
    description: "iPhone released.",
    time: [2007, null, null, null, null, null],
    emoji: "📱",
    groups: ["Human History", "Technology"],
    priority: 60,
  },
  {
    id: "covid",
    title: "COVID-19 Pandemic",
    description: "Global pandemic begins.",
    time: [2020, null, null, null, null, null],
    emoji: "😷",
    groups: ["Human History", "Recent"],
    priority: 65,
  },
  // ── Cosmic History ─────────────────────────────────────────────────────────
  {
    id: "first-stars",
    title: "First Stars",
    description: "First generation of stars ignite, ending the cosmic dark ages.",
    time: [-136000000000, null, null, null, null, null],
    emoji: "✨",
    groups: ["Cosmic History"],
    priority: 98,
  },
  {
    id: "milky-way-formed",
    title: "Milky Way Forms",
    description: "Our galaxy begins to take shape from gas clouds and early mergers.",
    time: [-10600000000, null, null, null, null, null],
    emoji: "🌀",
    groups: ["Cosmic History"],
    priority: 92,
  },
  {
    id: "solar-system-formed",
    title: "Solar System Forms",
    description: "Sun and planets coalesce from a protoplanetary disk.",
    time: [-4600000000, null, null, null, null, null],
    emoji: "☀️",
    groups: ["Cosmic History", "Earth History"],
    priority: 88,
  },
  {
    id: "moon-formed",
    title: "Moon Forms",
    description: "A Mars-sized body collides with Earth, ejecting debris that becomes the Moon.",
    time: [-4450000000, null, null, null, null, null],
    emoji: "🌙",
    groups: ["Cosmic History", "Earth History"],
    priority: 87,
  },
  {
    id: "first-oceans",
    title: "First Oceans",
    description: "Earth's surface cools enough for liquid water to pool.",
    time: [-4300000000, null, null, null, null, null],
    emoji: "🌊",
    groups: ["Earth History"],
    priority: 86,
  },
  {
    id: "first-oxygen",
    title: "Great Oxidation Event",
    description: "Cyanobacteria produce oxygen, reshaping Earth's atmosphere.",
    time: [-2400000000, null, null, null, null, null],
    emoji: "🫧",
    groups: ["Earth History", "Biology"],
    priority: 80,
  },
  {
    id: "eukaryotes",
    title: "Eukaryotes Appear",
    description: "Complex cells with nuclei emerge, enabling multicellular life.",
    time: [-2100000000, null, null, null, null, null],
    emoji: "🧬",
    groups: ["Earth History", "Biology"],
    priority: 78,
  },
  {
    id: "cambrian-explosion",
    title: "Cambrian Explosion",
    description: "Rapid diversification of complex animal life forms.",
    time: [-538800000, null, null, null, null, null],
    emoji: "🦀",
    groups: ["Earth History", "Biology"],
    priority: 83,
  },
  {
    id: "first-land-plants",
    title: "Plants Colonize Land",
    description: "Plants make the leap from water to solid ground.",
    time: [-470000000, null, null, null, null, null],
    emoji: "🌿",
    groups: ["Earth History", "Biology"],
    priority: 77,
  },
  {
    id: "first-mammals",
    title: "First Mammals",
    description: "Mammal ancestors emerge in the shadow of dinosaurs.",
    time: [-225000000, null, null, null, null, null],
    emoji: "🐾",
    groups: ["Earth History", "Biology"],
    priority: 75,
  },
  {
    id: "birds-evolve",
    title: "Birds Evolve",
    description: "Dinosaurs evolve into birds — the only surviving dinosaur lineage.",
    time: [-160000000, null, null, null, null, null],
    emoji: "🐦",
    groups: ["Earth History", "Biology"],
    priority: 72,
  },
  {
    id: "himalayas-rise",
    title: "Himalayas Rise",
    description: "India collides with Asia, building the world's tallest mountains.",
    time: [-45000000, null, null, null, null, null],
    emoji: "🏔️",
    groups: ["Earth History"],
    priority: 70,
  },
  {
    id: "first-hominins",
    title: "First Hominins",
    description: "Human lineage diverges from our common ancestor with chimpanzees.",
    time: [-7000000, null, null, null, null, null],
    emoji: "🧍",
    groups: ["Human History", "Biology"],
    priority: 68,
  },
  {
    id: "stone-tools",
    title: "Stone Tools",
    description: "Early humans start shaping stone into cutting tools.",
    time: [-3300000, null, null, null, null, null],
    emoji: "🪨",
    groups: ["Human History"],
    priority: 62,
  },
  {
    id: "fire-mastered",
    title: "Fire Mastered",
    description: "Controlled use of fire transforms diet and culture.",
    time: [-1000000, null, null, null, null, null],
    emoji: "🔥",
    groups: ["Human History"],
    priority: 65,
  },
  {
    id: "agriculture",
    title: "Agriculture",
    description: "Humans settle and farm — end of nomadic life begins.",
    time: [-12000, null, null, null, null, null],
    emoji: "🌾",
    groups: ["Human History"],
    priority: 72,
  },
  {
    id: "writing-invented",
    title: "Writing Invented",
    description: "Cuneiform in Mesopotamia — humanity's first records.",
    time: [-3400, null, null, null, null, null],
    emoji: "📜",
    groups: ["Human History", "Technology"],
    priority: 70,
  },
  {
    id: "bronze-age",
    title: "Bronze Age",
    description: "Metallurgy enables stronger tools, weapons, and trade.",
    time: [-3300, null, null, null, null, null],
    emoji: "⚔️",
    groups: ["Human History"],
    priority: 62,
  },
  {
    id: "iron-age",
    title: "Iron Age",
    description: "Iron smelting revolutionizes agriculture and warfare.",
    time: [-1200, null, null, null, null, null],
    emoji: "⛏️",
    groups: ["Human History"],
    priority: 60,
  },
  {
    id: "democracy-born",
    title: "Democracy Born",
    description: "Athens introduces direct democracy.",
    time: [-507, null, null, null, null, null],
    emoji: "🏺",
    groups: ["Human History", "Empires"],
    priority: 58,
  },
  {
    id: "alexander-empire",
    title: "Alexander's Empire",
    description: "Alexander the Great creates one of history's largest empires.",
    time: [-336, null, null, null, null, null],
    emoji: "👑",
    groups: ["Human History", "Empires"],
    priority: 56,
  },
  {
    id: "gupta-empire",
    title: "Gupta Empire",
    description: "Golden age of India — science, math, art, and literature flourish.",
    time: [320, null, null, null, null, null],
    emoji: "🪷",
    groups: ["Human History", "Empires"],
    priority: 54,
  },
  {
    id: "printing-press",
    title: "Printing Press",
    description: "Gutenberg's press democratizes knowledge and sparks revolution.",
    time: [1440, null, null, null, null, null],
    emoji: "📖",
    groups: ["Human History", "Technology"],
    priority: 68,
  },
  {
    id: "scientific-revolution",
    title: "Scientific Revolution",
    description: "Copernicus, Galileo, Newton — the birth of modern science.",
    time: [1543, null, null, null, null, null],
    emoji: "🔭",
    groups: ["Human History", "Technology"],
    priority: 65,
  },
  {
    id: "electricity",
    title: "Electricity Harnessed",
    description: "Practical electricity transforms every aspect of civilization.",
    time: [1882, null, null, null, null, null],
    emoji: "💡",
    groups: ["Human History", "Technology"],
    priority: 68,
  },
  {
    id: "world-war-1",
    title: "World War I",
    description: "The Great War reshapes the global political order.",
    time: [1914, null, null, null, null, null],
    emoji: "⚔️",
    groups: ["Human History", "Recent"],
    priority: 62,
  },
  {
    id: "world-war-2",
    title: "World War II",
    description: "Deadliest conflict in human history — 70+ million lives lost.",
    time: [1939, null, null, null, null, null],
    emoji: "💣",
    groups: ["Human History", "Recent"],
    priority: 63,
  },
  {
    id: "dna-discovered",
    title: "DNA Discovered",
    description: "Watson and Crick reveal the double helix — key to life's code.",
    time: [1953, null, null, null, null, null],
    emoji: "🧪",
    groups: ["Human History", "Biology", "Technology"],
    priority: 67,
  },
  {
    id: "human-genome",
    title: "Human Genome Mapped",
    description: "Complete human DNA sequence decoded — revolutionizing medicine.",
    time: [2003, null, null, null, null, null],
    emoji: "�🧬",
    groups: ["Human History", "Biology", "Technology"],
    priority: 65,
  },
  {
    id: "social-media",
    title: "Social Media",
    description: "Facebook launches — social networks reshape human communication.",
    time: [2004, null, null, null, null, null],
    emoji: "📱",
    groups: ["Human History", "Technology", "Recent"],
    priority: 58,
  },
  {
    id: "gpt-released",
    title: "GPT Released",
    description: "OpenAI releases GPT — the dawn of the large language model era.",
    time: [2018, null, null, null, null, null],
    emoji: "🤖",
    groups: ["Human History", "Technology", "Recent"],
    priority: 60,
  },
  {
    id: "chatgpt-launch",
    title: "ChatGPT Launches",
    description: "Conversational AI goes mainstream, reaching 100M users in two months.",
    time: [2022, null, null, null, null, null],
    emoji: "💬",
    groups: ["Human History", "Technology", "Recent"],
    priority: 65,
  },
];
